spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      url: jdbc:mysql://localhost:3306/mybatis-example
      username: root
      password: 666666
      driver-class-name: com.mysql.cj.jdbc.Driver



logging:
  level:
    root: debug

mybatis:
  mapper-locations: classpath:/mappers/*.xml
  type-aliases-package: com.wubai.entity
  configuration:
    map-underscore-to-camel-case: true
    auto-mapping-behavior: full
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl